package lt.vcs.vcs_project.UI;

public enum MenuTitle {
    TOP, ACCOUNT, STUDENT, LECTURER, COURSE, LIST_ACCOUNTS, PRINT_ACCOUNT,
    ADD_ACCOUNT, UPDATE_ACCOUNT, CHANGE_ACCOUNT_PASSWORD, REMOVE_ACCOUNT, LIST_STUDENTS,
    PRINT_STUDENT, ADD_STUDENT, UPDATE_STUDENT, CHANGE_STUDENT_PASSWORD, REMOVE_STUDENT,
    ASSIGN_COURSE, LIST_LECTURERS, PRINT_LECTURER, ADD_LECTURER, UPDATE_LECTURER, CHANGE_LECTURER_PASSWORD,
    REMOVE_LECTURER, LIST_COURSES, PRINT_COURSE, ADD_COURSE, UPDATE_COURSE, REMOVE_COURSE,
    ASSIGN_COURSE_STUDENT, ASSIGN_COURSE_LECTURER, LIST_ASSIGNED_COURSES,
    LOGOUT, loadsomedata
};

